algoritmo "areaquadrado"
// Função : este programa solicita e calcula um valor e calcula a área do quadrado
// Autor : Vitor Eduardo Matos Virginio
// Data : 01/03/2024
// Seção de Declarações 
var

areaQ: real
lado: real

inicio

//entrada

escreva("Qual o lado do quadrado?")
leia (Lado)

//processamento
AreaQ <- lado * lado


//saída

escreva("A are do quadrado é: ", areaQ)

fimalgoritmo
